/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Register.java
 *
 * Created on Mar 28, 2011, 10:42:43 AM
 */

/**
 *
 * @author Rahana,Anu,Sebin,Pratheesh
 */
 
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Register extends javax.swing.JFrame {

    /** Creates new form Register */
    public Register() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgReg = new javax.swing.JDialog();
        lblregister = new javax.swing.JLabel();
        lblUserreg = new javax.swing.JLabel();
        txtUserreg = new javax.swing.JTextField();
        lblPassreg = new javax.swing.JLabel();
        passreg = new javax.swing.JPasswordField();
        passregre = new javax.swing.JPasswordField();
        lblPassregre = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnCancelreg = new javax.swing.JButton();
        btnLoginreg = new javax.swing.JButton();
        lblLoginreg = new javax.swing.JLabel();
        lblNot = new javax.swing.JLabel();

        dlgReg.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgReg.setTitle("Dialogue");
        dlgReg.setAlwaysOnTop(true);

        javax.swing.GroupLayout dlgRegLayout = new javax.swing.GroupLayout(dlgReg.getContentPane());
        dlgReg.getContentPane().setLayout(dlgRegLayout);
        dlgRegLayout.setHorizontalGroup(
            dlgRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dlgRegLayout.setVerticalGroup(
            dlgRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        setBounds(new java.awt.Rectangle(460, 190, 0, 0));
        setResizable(false);

        lblregister.setFont(new java.awt.Font("Tahoma", 0, 24));
        lblregister.setText("Register");

        lblUserreg.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblUserreg.setText("Username");

        txtUserreg.setToolTipText("Enter your username..");
        txtUserreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserregActionPerformed(evt);
            }
        });

        lblPassreg.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblPassreg.setText("Password");

        passreg.setToolTipText("Enter your password..");

        passregre.setToolTipText("Retype your password..");

        lblPassregre.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblPassregre.setText("Retype Password");

        btnCreate.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnCreate.setText("Create");
        btnCreate.setToolTipText("Click here to create your account..");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnCancelreg.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnCancelreg.setText("Cancel");
        btnCancelreg.setToolTipText("Cancel");
        btnCancelreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelregActionPerformed(evt);
            }
        });

        btnLoginreg.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnLoginreg.setText("Login");
        btnLoginreg.setToolTipText("Click here to login with your existing account..");
        btnLoginreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginregActionPerformed(evt);
            }
        });

        lblLoginreg.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblLoginreg.setText("Already have an account?");

        lblNot.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lblregister))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblNot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUserreg)
                                    .addComponent(lblPassreg)
                                    .addComponent(lblPassregre))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passregre)
                                    .addComponent(passreg)
                                    .addComponent(txtUserreg, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnCreate)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCancelreg))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblLoginreg)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnLoginreg))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblregister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserreg)
                    .addComponent(txtUserreg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassreg)
                    .addComponent(passreg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passregre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassregre))
                .addGap(18, 18, 18)
                .addComponent(lblNot, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnCancelreg))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginreg)
                    .addComponent(btnLoginreg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
      
            String userreg = txtUserreg.getText();
            String passregg = passreg.getText();
            String passreggre = passregre.getText();
            if (passregg.equals(passreggre)&& !userreg.isEmpty()) {
                try {
            String strUrl = "jdbc:derby:Vo-Cal;user=app;password=app";
            Connection dbConnection = DriverManager.getConnection(strUrl);
            Statement stmt = dbConnection.createStatement();
                    stmt.executeUpdate("insert into APP.LOGINTABLE values('" + userreg + "','" + passregg + "')");
                    stmt.close();
                JOptionPane.showMessageDialog(this, "You have been registered.");
                //btnLoginreg.setFocusable(true);
                }
                catch (SQLException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                    lblNot.setText("Username exists. Try another..");
                    txtUserreg.setText("");
                    passreg.setText("");
                    passregre.setText("");
                }

            } else if (userreg.isEmpty() || passregg.isEmpty()) {
                lblNot.setText("Please enter anything!!");
                //txtUserreg.setFocusable(true);
            } else {
                txtUserreg.setText("");
                //txtUserreg.setFocusable(true);

                lblNot.setText("Password Mismatch!!");
                passreg.setText("");
                passregre.setText("");
            }
}//GEN-LAST:event_btnCreateActionPerformed

    private void btnLoginregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginregActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Home home=new Home();
        home.setVisible(true);
    }//GEN-LAST:event_btnLoginregActionPerformed

    private void btnCancelregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelregActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Home home=new Home();
        home.setVisible(true);
    }//GEN-LAST:event_btnCancelregActionPerformed

    private void txtUserregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserregActionPerformed
       
                  
      
    }//GEN-LAST:event_txtUserregActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelreg;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnLoginreg;
    private javax.swing.JDialog dlgReg;
    private javax.swing.JLabel lblLoginreg;
    private javax.swing.JLabel lblNot;
    private javax.swing.JLabel lblPassreg;
    private javax.swing.JLabel lblPassregre;
    private javax.swing.JLabel lblUserreg;
    private javax.swing.JLabel lblregister;
    private javax.swing.JPasswordField passreg;
    private javax.swing.JPasswordField passregre;
    private javax.swing.JTextField txtUserreg;
    // End of variables declaration//GEN-END:variables

}
